### ISSUE TITLE
[EXPIRED] Add Twig setup instructions

### ISSUE THREAD

**Issue by sergeevabc** [MattyO/Slim-Fizbuz#1]
Slim-Fizbuz does not work out of the box.
It fires as follows

```
Warning: Uncaught exception 'ErrorException' with message '
require_once(/usr/share/php5/PEAR/Twig/Autoloader.php) 
[function.require-once]: failed to open stream: 
No such file or directory' in D:\www\domains\localhost\libs\TwigView.php:87
Stack trace: #0 D:\www\domains\localhost\libs\TwigView.php(87):
Slim::handleErrors(2, 'require_once(/u...', 'D:\www\domains\...', 87, Array)
#1 D:\www\domains\localhost\libs\TwigView.php(87): TwigView::getEnvironment()
#2 D:\www\domains\localhost\libs\TwigView.php(73): TwigView->getEnvironment() 
#3 D:\www\domains\localhost\libs\Slim\View.php(144): TwigView->render('index.twig')
#4 D:\www\domains\localhost\libs\Slim\Slim.php(603): Slim_View->display('index.twig')
#5 D:\www\domains\localhost\index.php(45): Slim->render('index.twig', Array)
#6 [internal function]: {closure}()
#7 D:\www\domains\localhost\libs\Slim\Route.php(392): call_user_func_array(Object(Closure), Array)
#8 D:\www\domains\localhost\libs\Slim\Slim.php(1047): Slim_Route->dispatch()
#9 D:\www\domains\localhost\index.php(73): Slim->run()
#10 {main} thrown in D:\www\domains\localhost\libs\TwigView.php on line 87

Fatal error: TwigView::getEnvironment() [function.require]: 
Failed opening required '/usr/share/php5/PEAR/Twig/Autoloader.php' 
(include_path='.;D:/www/modules/php/PHP-5.3.23/;D:/www/modules/php/PHP-5.3.23/PEAR') 
in D:\www\domains\localhost\libs\TwigView.php on line 87
```

Obviously Twig is missing, but there are no instructions where to place it.

**Comment by MattyO** [comment]
Thanks for the comment.  I'll take a look in a few hours and provide fresh install instructions using vagrant

**Comment by sergeevabc** [comment]
A few hours passed, I guess. Is this issue resolved?
